export const SUPPORTED_LANGUAGES = {
  "VI-VN": "Tiếng Việt",
  "EN-US": "English (US)", 
  "EN-GB": "English (UK)",
  "FR-FR": "Français",
  "FR-CA": "Français (Canada)", 
  "ES-ES": "Español",
  "ES-MX": "Español (México)",
  "DE-DE": "Deutsch",
  "IT-IT": "Italiano",
  "PT-PT": "Português",
  "PT-BR": "Português (Brasil)",
  "JA-JP": "日本語",
  "ZH-CN": "简体中文",
  "ZH-TW": "繁體中文",
  "RU-RU": "Русский",
  "AR-SA": "العربية",
  "KO-KR": "한국어",
  "TR-TR": "Türkçe",
  "NL-NL": "Nederlands",
  "SV-SE": "Svenska", 
  "DA-DK": "Dansk",
  "NO-NO": "Norsk",
  "FI-FI": "Suomi"
};
