name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*'  # Chạy khi có tag version như "v1.0", "v2.1",...

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files in Send-to-AI
        run: ls -la Send-to-AI  # In danh sách các tệp trong thư mục

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./Send-to-AI

      - name: Generate .zip file
        run: |
          zip -r extension.zip * -x ".git/*"
        working-directory: ./Send-to-AI

      - name: Generate .crx file
        run: |
          openssl genrsa -out key.pem 2048
          openssl req -new -key key.pem -out csr.pem -subj "/CN=Chrome Extension"
          openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out cert.pem
          cat cert.pem key.pem > extension.crx
        working-directory: ./Send-to-AI

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload .zip file to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Send-to-AI/extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip

      - name: Upload .crx file to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Send-to-AI/extension.crx
          asset_name: extension.crx
          asset_content_type: application/octet-stream
