jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Không chỉ định `working-directory` nếu `package.json` ở thư mục gốc
      - name: Install dependencies
        run: npm install

      - name: Generate .zip file
        run: |
          zip -r extension.zip * -x ".git/*"

      - name: Generate .crx file
        run: |
          openssl genrsa -out key.pem 2048
          openssl req -new -key key.pem -out csr.pem -subj "/CN=Chrome Extension"
          openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out cert.pem
          cat cert.pem key.pem > extension.crx

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload .zip file to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip

      - name: Upload .crx file to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.crx
          asset_name: extension.crx
          asset_content_type: application/octet-stream
